import {test,after} from "node:test";
import assert from "node:assert/strict";
import {promises as fs} from "node:fs";
import path from "node:path";
import os from "node:os";
process.env.OMNI_ENABLED="true";
import {omniApi} from "../src/routes/omni";
import {config} from "../src/config";
import {resetDb,makeSession,sessionCookie} from "./helpers";
let root:string|undefined;
after(async()=>{delete process.env.OMNI_SKILLS_DIR;if(root)await fs.rm(root,{recursive:true,force:true});});
test("skills routes are owner-only and preserve revision conflicts",async()=>{
 resetDb();
 root=await fs.mkdtemp(path.join(os.tmpdir(),"omni-skills-route-"));process.env.OMNI_SKILLS_DIR=root;
 await fs.mkdir(path.join(root,"sample"));await fs.writeFile(path.join(root,"sample","SKILL.md"),"Instructions");
 const J={"content-type":"application/json"};
 const owner={...J,cookie:sessionCookie(makeSession(config.ownerEmail))};
 const other={...J,cookie:sessionCookie(makeSession("other@example.com"))};
 assert.equal((await omniApi.request("/skills")).status,401);
 assert.equal((await omniApi.request("/skills",{headers:other})).status,403);
 const list=await (await omniApi.request("/skills",{headers:owner})).json() as {skills:{id:string}[]};const id=list.skills[0]!.id;
 const detail=await (await omniApi.request(`/skills/${id}`,{headers:owner})).json() as {skill:{revision:string;text:string}};
 const save=(text:string,revision:string,headers=owner)=>omniApi.request(`/skills/${id}`,{method:"PUT",headers,body:JSON.stringify({text,revision})});
 assert.equal((await save("Forged",detail.skill.revision,other)).status,403);
 assert.equal((await save("Updated",detail.skill.revision)).status,200);
 assert.equal((await save("Stale",detail.skill.revision)).status,409);
 assert.equal(await fs.readFile(path.join(root,"sample","SKILL.md"),"utf8"),"Updated");
 assert.equal((await omniApi.request("/skills/../../secret",{headers:owner})).status,404);
});
