import { test, expect, type Locator } from "@playwright/test";
const height = (input: Locator) => input.evaluate(el => el.getBoundingClientRect().height);
const long = Array.from({length:18},(_,i)=>`Draft line ${i+1}: keep these details.`).join("\n");
for (const width of [1440,390,320]) test(`composer grows, caps and shrinks without replacing its field at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:900});
 await page.goto("/e2e-fixtures/messages.html");
 const input=page.getByRole("textbox",{name:"Message",exact:true});
 await expect(input).toBeVisible();
 await expect.poll(()=>height(input)).toBe(44);
 await input.fill("First line\nSecond line\nThird line");
 await expect.poll(()=>height(input)).toBeGreaterThan(44);
 await input.fill(long);
 await expect.poll(()=>height(input)).toBe(160);
 await expect(input).toHaveCSS("overflow-y","auto");
 expect(await input.evaluate(el=>el.scrollHeight>el.clientHeight)).toBe(true);
 await input.evaluate(el=>{(window as any).originalComposer=el;});
 await input.focus();await input.press("ControlOrMeta+End");
 await page.screenshot({path:test.info().outputPath(`composer-grown-${width}.png`)});
 await input.fill("A short reply");
 await expect.poll(()=>height(input)).toBe(44);
 await expect(input).toHaveCSS("overflow-y","hidden");
 await expect(input).toBeFocused();
 expect(await input.evaluate(el=>(window as any).originalComposer===el)).toBe(true);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test("width changes remeasure the same focused textarea and preserve caret and draft",async({page})=>{
 await page.setViewportSize({width:1440,height:900});
 await page.goto("/e2e-fixtures/messages.html");
 const input=page.getByRole("textbox",{name:"Message",exact:true});
 const body="A deliberate reply with enough text to wrap on a phone but fit on one desktop line. ".repeat(2);
 await input.fill(body);const wide=await height(input);
 await input.evaluate(el=>{(el as HTMLTextAreaElement).setSelectionRange(18,26);(window as any).originalComposer=el;});
 await page.setViewportSize({width:390,height:900});
 await expect.poll(()=>height(input)).toBeGreaterThan(wide);
 await expect(input).toHaveValue(body);await expect(input).toBeFocused();
 expect(await input.evaluate(el=>[(el as HTMLTextAreaElement).selectionStart,(el as HTMLTextAreaElement).selectionEnd])).toEqual([18,26]);
 await page.setViewportSize({width:1440,height:900});
 await expect.poll(()=>height(input)).toBe(wide);
 expect(await input.evaluate(el=>(window as any).originalComposer===el)).toBe(true);
});
test("restored multiline drafts grow only for their account and conversation",async({page})=>{
 await page.goto("/e2e-fixtures/messages.html");
 const input=page.getByRole("textbox",{name:"Message",exact:true});
 await input.fill(long);await page.reload();
 await expect(input).toHaveValue(long);await expect.poll(()=>height(input)).toBe(160);
 await page.getByRole("button",{name:"Room B",exact:true}).click();
 await expect(input).toHaveValue("");await expect.poll(()=>height(input)).toBe(44);
 await page.getByRole("button",{name:"Room A",exact:true}).click();
 await expect(input).toHaveValue(long);await expect.poll(()=>height(input)).toBe(160);
 await page.getByRole("button",{name:"Morgan account",exact:true}).click();
 await expect(input).toHaveValue("");await expect.poll(()=>height(input)).toBe(44);
 await page.getByRole("button",{name:"Alex account",exact:true}).click();
 await expect(input).toHaveValue(long);await expect.poll(()=>height(input)).toBe(160);
});
test("failed send retains expanded draft and confirmed send clears and shrinks it",async({page})=>{
 await page.goto("/e2e-fixtures/messages.html");
 const input=page.getByRole("textbox",{name:"Message",exact:true});
 await input.fill(long);await page.getByRole("button",{name:"Send message",exact:true}).click();
 await expect(page.getByRole("alert")).toContainText("Your draft is kept");
 await expect(input).toHaveValue(long);await expect.poll(()=>height(input)).toBe(160);
 await page.evaluate(()=>(window as any).prismMessagesFixture.reject=false);
 await page.getByRole("button",{name:"Send message",exact:true}).click();
 await expect(input).toHaveValue("");await expect.poll(()=>height(input)).toBe(44);await expect(input).toBeFocused();
 expect(await page.evaluate(()=>(window as any).prismMessagesFixture.attempts)).toBe(2);
});
test("composition Enter never sends and Shift+Enter grows the current draft",async({page})=>{
 await page.goto("/e2e-fixtures/messages.html");
 const input=page.getByRole("textbox",{name:"Message",exact:true});
 await input.fill("Draft under composition");
 await input.dispatchEvent("compositionstart");
 await input.dispatchEvent("keydown",{key:"Enter",code:"Enter",isComposing:true,bubbles:true});
 await input.dispatchEvent("compositionend",{data:"Draft under composition"});
 expect(await page.evaluate(()=>(window as any).prismMessagesFixture.attempts)).toBe(0);
 await input.press("ControlOrMeta+End");await input.press("Shift+Enter");await input.press("Shift+Enter");
 await expect.poll(()=>height(input)).toBeGreaterThan(44);
 await expect(input).toHaveValue("Draft under composition\n\n");
 expect(await page.evaluate(()=>(window as any).prismMessagesFixture.attempts)).toBe(0);
});
test("typing beyond the height cap follows the caret while middle edits retain their position",async({page})=>{
 await page.setViewportSize({width:390,height:900});await page.goto("/e2e-fixtures/messages.html");
 const input=page.getByRole("textbox",{name:"Message",exact:true});
 await input.fill(long);await input.press("ControlOrMeta+End");
 for(let i=0;i<5;i++){await input.press("Shift+Enter");await input.pressSequentially(`Added detail ${i}`);}
 await expect.poll(()=>input.evaluate(el=>el.scrollHeight-el.clientHeight-el.scrollTop)).toBeLessThan(25);
 const middle=await input.evaluate(el=>{const field=el as HTMLTextAreaElement;const at=field.value.indexOf("Draft line 9:");field.setSelectionRange(at,at);field.scrollTop=field.scrollHeight/2-field.clientHeight/2;return {at,top:field.scrollTop};});
 await input.pressSequentially("Edited ");
 expect(await input.evaluate(el=>(el as HTMLTextAreaElement).selectionStart)).toBe(middle.at+7);
 expect(Math.abs(await input.evaluate(el=>el.scrollTop)-middle.top)).toBeLessThan(50);
 await expect.poll(()=>height(input)).toBe(160);
});
