import { test, expect } from "@playwright/test";
import { Server } from "@hocuspocus/server";
import WebSocket from "ws";

test("page properties preserve the editor and failed title changes remain recoverable", async ({ page }, info) => {
  await page.goto("/e2e-fixtures/workspace.html");
  const editor = page.locator('.tiptap[contenteditable=true]');
  await expect(editor).toBeVisible();
  await editor.evaluate(node => { (window as any).originalWritingEditor = node; });
  await page.locator('.document-properties-disclosure summary').click();
  await expect(page.locator('.document-properties-content')).toContainText('Projects/Prism/A living workspace');
  await expect(page.locator('.document-property-tag')).toHaveText('project');
  expect(await editor.evaluate(node => node === (window as any).originalWritingEditor)).toBe(true);
  await page.evaluate(() => { (window as any).prismFixtureControls.rejectWrite = true; });
  await page.getByRole('button', { name: 'Rename A living workspace', exact: true }).click();
  const title = page.getByRole('textbox', { name: 'Document title' });
  await title.fill('A clearer workspace');
  await title.press('Enter');
  await expect(page.getByRole('alert').filter({ hasText: 'Could not rename this page' })).toBeVisible();
  await expect(title).toHaveValue('A clearer workspace');
  await expect(title).toBeFocused();
  await page.evaluate(() => { (window as any).prismFixtureControls.rejectWrite = false; });
  await title.press('Enter');
  await expect(page.getByRole('button', { name: 'Rename A clearer workspace', exact: true })).toBeVisible();
  await expect(page.locator('.document-properties-content')).toContainText('Projects/Prism/A clearer workspace');
  expect(await editor.evaluate(node => node === (window as any).originalWritingEditor)).toBe(true);
  await page.screenshot({ path: info.outputPath('document-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator('.document-page-header')).toBeVisible();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath('document-phone.png'), fullPage: true });
});

test("outline opens without moving the selection, follows heading edits and navigates the same editor", async ({ page }, info) => {
  await page.goto('/e2e-fixtures/workspace.html');
  const editor = page.locator('.tiptap[contenteditable=true]');
  await expect(editor).toBeVisible();
  await editor.locator('h2').first().click();
  const selection = await page.evaluate(() => { const s = getSelection()!; return { text: s.anchorNode?.textContent, offset: s.anchorOffset }; });
  const scroll = await page.locator('.document-writing-scroll').evaluate(node => node.scrollTop);
  await page.getByRole('button', { name: 'Outline', exact: true }).click();
  const outline = page.getByRole('navigation', { name: 'Document outline' });
  await expect(outline.getByRole('button', { name: 'Purpose', exact: true })).toBeVisible();
  expect(await page.evaluate(() => { const s = getSelection()!; return { text: s.anchorNode?.textContent, offset: s.anchorOffset }; })).toEqual(selection);
  expect(await page.locator('.document-writing-scroll').evaluate(node => node.scrollTop)).toBe(scroll);
  await page.screenshot({ path: info.outputPath('outline-desktop.png'), fullPage: true });
  await page.keyboard.press('Escape');
  await expect(outline).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Outline', exact: true })).toBeFocused();
  await page.getByRole('button', { name: 'Outline', exact: true }).click();
  await outline.getByRole('button', { name: 'Next steps', exact: true }).click();
  await expect(outline).toHaveCount(0);
  expect(await page.locator('.document-writing-scroll').evaluate(node => node.scrollTop)).toBeGreaterThan(scroll);
  await editor.locator('h2').last().click();
  await page.keyboard.press('End');
  await page.keyboard.type(' together');
  await page.getByRole('button', { name: 'Outline', exact: true }).click();
  await expect(outline.getByRole('button', { name: 'Next steps together', exact: true })).toBeVisible();
  await outline.getByRole('button', { name: 'Next steps together', exact: true }).focus();
  await page.keyboard.press('Escape');
  await expect(outline).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Outline', exact: true })).toBeFocused();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => { document.documentElement.classList.remove('light'); document.documentElement.classList.add('dark'); });
  await page.getByRole('button', { name: 'Outline', exact: true }).click();
  await expect(outline).toBeVisible();
  await page.screenshot({ path: info.outputPath('outline-phone-dark.png'), fullPage: true, animations: 'disabled' });
});

test("formatting is discoverable, preserves selection and remembers the full toolbar preference", async ({ page }) => {
  await page.goto('/e2e-fixtures/workspace.html');
  const editor = page.locator('.tiptap[contenteditable=true]');
  await expect(editor).toBeVisible();
  await editor.fill('Selected writing');
  await editor.press('ControlOrMeta+Alt+0');
  await page.getByRole('button', { name: 'Outline', exact: true }).click();
  await expect(page.getByRole('navigation', { name: 'Document outline' })).toContainText('Add headings to navigate this page.');
  await page.getByRole('button', { name: 'Outline', exact: true }).click();
  await editor.press('ControlOrMeta+a');
  const formatting = page.getByRole('button', { name: 'Formatting', exact: true });
  await expect(formatting).toHaveAttribute('aria-expanded', 'false');
  await formatting.click();
  await page.getByRole('group', { name: 'Text formatting' }).getByRole('button', { name: /Bold/ }).click();
  await expect(editor.locator('strong')).toHaveText('Selected writing');
  await page.getByRole('checkbox', { name: 'Always show formatting toolbar' }).check();
  await formatting.click();
  await expect(formatting).toHaveAttribute('aria-expanded', 'false');
  await page.reload();
  await expect(formatting).toHaveAttribute('aria-expanded', 'true');
  await page.getByRole('checkbox', { name: 'Always show formatting toolbar' }).uncheck();
  await page.reload();
  await expect(formatting).toHaveAttribute('aria-expanded', 'false');
});

test("real collaborative host shares properties and readable mobile header without replacing its live editor", async ({ page }, info) => {
  const server = new Server({ address: '127.0.0.1', port: 0, quiet: true, debounce: 10, async onAuthenticate() { return { fixture: true }; } });
  await server.listen();
  const sockets: WebSocket[] = [];
  const path = 'Projects/Prism/A collaborative workspace with connected ideas';
  let level = 'own';
  try {
    await page.routeWebSocket(/\/collab$/, route => {
      const socket = new WebSocket(server.webSocketURL); sockets.push(socket);
      const pending: (string | Buffer)[] = [];
      route.onMessage(message => socket.readyState === WebSocket.OPEN ? socket.send(message) : pending.push(message));
      socket.on('open', () => { for (const message of pending) socket.send(message); });
      socket.on('message', (message, binary) => route.send(binary ? Buffer.from(message as Buffer) : message.toString()));
      route.onClose(() => socket.close()); socket.on('close', () => route.close({ code: 1000 }));
    });
    await page.route('**/auth/me', route => route.fulfill({ json: { authenticated: true, email: 'alice@example.test', vaultId: 'primary', workspace: { id: 'workspace-a' } } }));
    await page.route('**/api/notes/denied-note', route => route.fulfill({ json: { id: 'denied-note', path, content: '', _level: level, metadata: {}, tags: [] } }));
    await page.route('**/api/federated/**', route => route.fulfill({ status: 204 }));
    await page.goto('/e2e-fixtures/collab-storage.html?live');
    const editor = page.locator('.tiptap[contenteditable=true]');
    await expect(editor).toBeVisible();
    await editor.fill('Our shared ideas stay connected.');
    const formatting = page.getByRole('button', { name: 'Formatting', exact: true });
    await expect(formatting).toHaveAttribute('aria-expanded', 'false');
    await expect(page.getByRole('button', { name: 'Editing', exact: true })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Accept all suggestions', exact: true })).toBeVisible();
    await editor.press('ControlOrMeta+a');
    await formatting.click();
    await page.getByRole('group', { name: 'Text formatting' }).getByRole('button', { name: 'Bold', exact: true }).click();
    await expect(editor.locator('strong')).toHaveText('Our shared ideas stay connected.');
    await page.getByRole('checkbox', { name: 'Always show formatting toolbar' }).check();
    await page.reload();
    await expect(formatting).toHaveAttribute('aria-expanded', 'true');
    await expect(editor.locator('strong')).toHaveText('Our shared ideas stay connected.');
    await formatting.click();
    await editor.evaluate(node => { (window as any).originalWritingEditor = node; });
    await page.locator('.document-properties-disclosure summary').click();
    await expect(page.locator('.document-properties-content')).toContainText(path);
    await expect(page.getByText('Live · Editing', { exact: true })).toBeVisible();
    await page.screenshot({ path: info.outputPath('collaborative-desktop.png'), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(editor).toHaveText('Our shared ideas stay connected.');
    expect(await editor.evaluate(node => node === (window as any).originalWritingEditor)).toBe(true);
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: info.outputPath('collaborative-phone.png'), fullPage: true });
    await editor.click();
    await formatting.click();
    await page.getByRole('group', { name: 'Text formatting' }).getByRole('button', { name: 'Heading 2', exact: true }).click();
    await expect(editor.locator('h2')).toHaveText('Our shared ideas stay connected.');
    await page.getByRole('button', { name: 'Outline', exact: true }).click();
    await expect(page.getByRole('navigation', { name: 'Document outline' })).toContainText('Our shared ideas stay connected.');
    await editor.locator('h2').click();
    await page.keyboard.press('End');
    await page.keyboard.type(' Together.');
    await page.getByRole('button', { name: 'Outline', exact: true }).click();
    await expect(page.getByRole('navigation', { name: 'Document outline' })).toContainText('Together.');
    level = 'view';
    await page.reload();
    await expect(page.locator('.tiptap[contenteditable=false]')).toBeVisible();
    await expect(formatting).toHaveCount(0);
    await expect(page.getByRole('button', { name: /^Rename / })).toHaveCount(0);
    await expect(page.locator('.document-properties-disclosure summary')).toBeVisible();
    const readonlyBody = await page.locator('.tiptap').innerHTML();
    await page.getByRole('button', { name: 'Outline', exact: true }).click();
    await page.getByRole('navigation', { name: 'Document outline' }).getByRole('button', { name: /Our shared ideas/ }).click();
    expect(await page.locator('.tiptap').innerHTML()).toBe(readonlyBody);
    await page.goto('/e2e-fixtures/workspace.html');
    await expect(page.getByRole('button', { name: 'Formatting', exact: true })).toHaveAttribute('aria-expanded', 'true');
    await page.goto('about:blank');
  } finally { for (const socket of sockets) socket.terminate(); await server.destroy(); }
});
