#!/usr/bin/env bash
#
# Governance e2e — boots a disposable Prism Server (own port + own db), serves
# the built web app, and runs the Playwright governance spec against it in a
# real browser. Never touches a running Prism service.
#
#   ./scripts/e2e-governance.sh                 # real vault (reuses apps/server/.env)
#   E2E_FAKE_VAULT=1 ./scripts/e2e-governance.sh  # no vault needed (CI/sandbox)
#
# Options via env:
#   E2E_PORT=8790        server port for the test stack
#   E2E_BUILD=1          force a fresh web build (default: build only if missing)
#   E2E_HEADED=1         run the browser headed
#
# The spec signs in via the real magic-link flow: the server (no RESEND key)
# prints the link to its log, which the spec reads (E2E_SERVER_LOG).

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SERVER_DIR="$ROOT/apps/server"
WEB_DIR="$ROOT/apps/web"
PORT="${E2E_PORT:-8790}"
FAKE_PORT="${FAKE_VAULT_PORT:-8791}"
LOG="${TMPDIR:-/tmp}/prism-e2e-governance.log"
ENV_E2E="$SERVER_DIR/.env.e2e"

say()  { printf '\033[1;36m[e2e]\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31m[e2e]\033[0m %s\n' "$*" >&2; exit 1; }

[ -d "$ROOT/node_modules" ] || fail "node_modules missing — run 'npm install' in $ROOT first."

port_busy() { (exec 3<>"/dev/tcp/127.0.0.1/$1") 2>/dev/null && { exec 3>&- 3<&-; return 0; } || return 1; }
port_busy "$PORT" && fail "port $PORT busy — set E2E_PORT to a free one."

PIDS=()
cleanup() {
  for pid in "${PIDS[@]:-}"; do kill "$pid" 2>/dev/null || true; done
  wait 2>/dev/null || true
}
trap cleanup EXIT INT TERM

# ── env for the disposable server ─────────────────────────────────────────────
if [ "${E2E_FAKE_VAULT:-0}" = "1" ]; then
  port_busy "$FAKE_PORT" && fail "fake-vault port $FAKE_PORT busy — set FAKE_VAULT_PORT."
  say "starting fake vault on :$FAKE_PORT"
  FAKE_VAULT_PORT="$FAKE_PORT" node "$ROOT/scripts/e2e/fake-vault.mjs" >> "$LOG.vault" 2>&1 &
  PIDS+=($!)
  cat > "$ENV_E2E" <<EOF
# generated by scripts/e2e-governance.sh (fake-vault mode)
PARACHUTE_URL=http://127.0.0.1:$FAKE_PORT
PARACHUTE_VAULT=default
PARACHUTE_TOKEN=e2e-fake-vault-token
SESSION_SECRET=e2e-session-secret-not-production
CAPABILITY_SECRET=e2e-capability-secret-not-production
COLLAB_TOKEN=e2e-collab-token
OWNER_EMAIL=owner@test.local
EOF
else
  # Real-vault mode: borrow config (worktree-aware, like governance-sandbox.sh).
  SRC_ENV="$SERVER_DIR/.env"
  if [ ! -f "$SRC_ENV" ]; then
    MAIN_WT="$(git -C "$ROOT" worktree list --porcelain 2>/dev/null | awk '/^worktree /{print $2; exit}')"
    [ -n "$MAIN_WT" ] && [ -f "$MAIN_WT/apps/server/.env" ] && SRC_ENV="$MAIN_WT/apps/server/.env"
  fi
  [ -f "$SRC_ENV" ] || fail "apps/server/.env not found (and no main-worktree copy) — or use E2E_FAKE_VAULT=1."
  grep -vE '^(PORT|DB_PATH|APP_ORIGIN|RESEND_API_KEY)=' "$SRC_ENV" > "$ENV_E2E"
fi
{
  echo "PORT=$PORT"
  echo "DB_PATH=./prism-server.e2e.db"
  echo "APP_ORIGIN=http://localhost:$PORT"
} >> "$ENV_E2E"
chmod 600 "$ENV_E2E"
rm -f "$SERVER_DIR/prism-server.e2e.db"*

# ── web build (server serves ../web/dist) ─────────────────────────────────────
if [ "${E2E_BUILD:-0}" = "1" ] || [ ! -f "$WEB_DIR/dist/index.html" ]; then
  say "building web app…"
  (cd "$ROOT" && npm run build -w @prism/web >/dev/null)
fi

# ── server ────────────────────────────────────────────────────────────────────
: > "$LOG"
say "starting e2e server on :$PORT (log: $LOG)"
(cd "$SERVER_DIR" && exec node --env-file=.env.e2e --import tsx src/index.ts) >> "$LOG" 2>&1 &
PIDS+=($!)
for i in $(seq 1 60); do
  if curl -s --noproxy '*' -o /dev/null "http://localhost:$PORT/auth/me" 2>/dev/null; then break; fi
  sleep 0.5
  [ "$i" = 60 ] && { tail -20 "$LOG"; fail "server not ready"; }
done

# ── playwright ────────────────────────────────────────────────────────────────
# Which specs to run: the commons flows that work against the (fake or real)
# vault. Override with E2E_SPECS="e2e/foo.spec.ts".
SPECS="${E2E_SPECS:-e2e/governance.spec.ts e2e/bioregion.spec.ts}"
say "running specs: $SPECS"
HEADED=()
[ "${E2E_HEADED:-0}" = "1" ] && HEADED=(--headed)
(
  cd "$WEB_DIR" &&
  E2E_BASE_URL="http://localhost:$PORT" \
  E2E_SERVER_LOG="$LOG" \
  PARACHUTE_TOKEN="$(grep -E '^PARACHUTE_TOKEN=' "$ENV_E2E" | cut -d= -f2-)" \
  COLLAB_TOKEN="$(grep -E '^COLLAB_TOKEN=' "$ENV_E2E" | cut -d= -f2- || true)" \
  OWNER_EMAIL="$(grep -E '^OWNER_EMAIL=' "$ENV_E2E" | cut -d= -f2-)" \
  npx playwright test $SPECS --reporter=list "${HEADED[@]}"
)
say "commons e2e PASSED"
