#!/usr/bin/env bash
#
# Governance sandbox — run the NEW governance server + web UI locally WITHOUT
# touching the Prism service you already have running (pm2 / port 8787).
#
#   ./scripts/governance-sandbox.sh
#
# What it does:
#   1. Builds apps/server/.env.sandbox from your existing apps/server/.env,
#      overriding: PORT=8899 (not 8787), DB_PATH=prism-server.sandbox.db (its
#      own sessions/grants — your real server db is untouched), APP_ORIGIN=
#      http://localhost:5180 (the Vite dev origin), and RESEND_API_KEY unset so
#      the owner magic link ALWAYS prints to this terminal instead of emailing.
#   2. Starts the sandbox server on :8899 (refuses to start if the port is
#      busy — it never kills anything).
#   3. Starts the Vite web dev server on :5180 with PRISM_SERVER pointing at
#      the sandbox, so /api + /auth proxy to it.
#   4. Watches the server log and prints any magic sign-in link loudly.
#
# Then open  http://localhost:5180/governance  and request a sign-in link with
# your OWNER_EMAIL — the link appears in THIS terminal; open it, and you're in.
#
# Notes:
#   - The sandbox talks to the SAME Parachute vault as your real server, so
#     governance artifacts are real notes (that is the design — governance state
#     is dogfooded as governed notes). To reset a test run, delete the notes
#     tagged governance-config / governance-role / governance-policy /
#     governance-membership / governance-proposal / governance-vote /
#     governance-audit.
#   - Ctrl-C stops everything the script started (and nothing else).
#   - Override the sandbox port with SANDBOX_PORT=9001 ./scripts/... if 8899
#     happens to be taken.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SERVER_DIR="$ROOT/apps/server"
PORT="${SANDBOX_PORT:-8899}"
WEB_PORT=5180
LOG="${TMPDIR:-/tmp}/prism-governance-sandbox.log"

say()  { printf '\033[1;36m[sandbox]\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31m[sandbox]\033[0m %s\n' "$*" >&2; exit 1; }

# Worktree-friendly: if this checkout has no apps/server/.env (it's gitignored,
# so a fresh `git worktree add` won't have one), borrow it from the MAIN
# worktree — the sandbox reuses your existing server config (PARACHUTE_TOKEN
# etc.) without you copying anything.
if [ ! -f "$SERVER_DIR/.env" ]; then
  MAIN_WT="$(git -C "$ROOT" worktree list --porcelain 2>/dev/null | awk '/^worktree /{print $2; exit}')"
  if [ -n "$MAIN_WT" ] && [ "$MAIN_WT" != "$ROOT" ] && [ -f "$MAIN_WT/apps/server/.env" ]; then
    cp "$MAIN_WT/apps/server/.env" "$SERVER_DIR/.env"
    chmod 600 "$SERVER_DIR/.env"
    say "copied apps/server/.env from your main checkout ($MAIN_WT)"
  else
    fail "apps/server/.env not found — copy it from your main checkout: cp <main-repo>/apps/server/.env apps/server/.env"
  fi
fi
[ -d "$ROOT/node_modules" ] || fail "node_modules missing — run 'npm install' in $ROOT first."

# Refuse to start if the sandbox port is already in use. We NEVER kill anything.
if (exec 3<>"/dev/tcp/127.0.0.1/$PORT") 2>/dev/null; then
  exec 3>&- 3<&- || true
  fail "port $PORT is already in use. Pick another: SANDBOX_PORT=9001 $0"
fi
if (exec 3<>"/dev/tcp/127.0.0.1/$WEB_PORT") 2>/dev/null; then
  exec 3>&- 3<&- || true
  fail "port $WEB_PORT (Vite) is already in use — stop that dev server first (the sandbox needs it for the web UI)."
fi

# ── 1. sandbox env: copy .env, override the isolation-critical keys ──────────
ENV_SANDBOX="$SERVER_DIR/.env.sandbox"
grep -vE '^(PORT|DB_PATH|APP_ORIGIN|RESEND_API_KEY)=' "$SERVER_DIR/.env" > "$ENV_SANDBOX"
{
  echo ""
  echo "# ── sandbox overrides (generated by scripts/governance-sandbox.sh) ──"
  echo "PORT=$PORT"
  echo "DB_PATH=./prism-server.sandbox.db"
  echo "APP_ORIGIN=http://localhost:$WEB_PORT"
  # no RESEND_API_KEY → magic links print to the console below
} >> "$ENV_SANDBOX"
chmod 600 "$ENV_SANDBOX"
say "wrote $ENV_SANDBOX (port $PORT, own db, console magic links)"

# ── 2. start the sandbox server ───────────────────────────────────────────────
: > "$LOG"
( cd "$SERVER_DIR" && exec node --env-file=.env.sandbox --import tsx src/index.ts ) >> "$LOG" 2>&1 &
SERVER_PID=$!

TAIL_PID=""
cleanup() {
  say "shutting down sandbox (server pid $SERVER_PID)…"
  [ -n "$TAIL_PID" ] && kill "$TAIL_PID" 2>/dev/null || true
  kill "$SERVER_PID" 2>/dev/null || true
  wait "$SERVER_PID" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

say "waiting for the sandbox server on :$PORT …"
for i in $(seq 1 60); do
  # Any HTTP response means the server is up (/auth/me answers 401 signed-out —
  # that still proves liveness, so no -f here).
  if curl -s --noproxy '*' -o /dev/null "http://localhost:$PORT/auth/me" 2>/dev/null; then break; fi
  kill -0 "$SERVER_PID" 2>/dev/null || { echo "── server log ──"; tail -20 "$LOG"; fail "sandbox server exited during startup (log: $LOG)"; }
  sleep 0.5
  [ "$i" = 60 ] && { echo "── server log ──"; tail -20 "$LOG"; fail "server did not become ready (log: $LOG)"; }
done
say "sandbox server is up: http://localhost:$PORT  (log: $LOG)"

# ── 3. surface magic links from the server log, loudly ───────────────────────
( tail -n0 -F "$LOG" 2>/dev/null | grep --line-buffered -o 'http[^" ]*auth/callback[^" ]*' | while read -r link; do
    printf '\n\033[1;33m════════════════════════════════════════════════════════\033[0m\n'
    printf '\033[1;33m  MAGIC SIGN-IN LINK → %s\033[0m\n' "$link"
    printf '\033[1;33m════════════════════════════════════════════════════════\033[0m\n\n'
  done ) &
TAIL_PID=$!

OWNER="$(grep -E '^OWNER_EMAIL=' "$ENV_SANDBOX" | cut -d= -f2- || true)"
say ""
say "READY. Open  http://localhost:$WEB_PORT/commons   (Bioregion + Governance)"
say "Sign in with your owner email (${OWNER:-see .env}) — the magic link will"
say "print RIGHT HERE in this terminal (yellow banner). Ctrl-C stops the sandbox."
say ""
say "Want example content to walk through? In another terminal:"
say "    node scripts/seed-demo-commons.mjs          # populate a demo Front Range commons"
say "    node scripts/seed-demo-commons.mjs --clean  # remove it"
say ""

# ── 4. web dev server (foreground; Ctrl-C tears everything down) ─────────────
# No `exec` — the EXIT trap above must survive to stop the sandbox server.
cd "$ROOT"
PRISM_SERVER="http://localhost:$PORT" npm run dev -w @prism/web
