#!/usr/bin/env bash
#
# two-hub-mock.sh — run the LIVE two-hub federation convergence harness
# (apps/server/scripts/verify-two-hub.ts) against a fully MOCKED substrate:
# two real Prism Servers, each fronting its own in-memory fake Parachute
# (scripts/e2e/fake-vault.mjs). No real vault, no network egress, nothing
# touched outside this script — ideal for sandboxes/CI and for building the
# federation-dependent plan items (G5) without live infrastructure.
#
#   ./scripts/two-hub-mock.sh          # bring up A+B, run the harness, tear down
#   ./scripts/two-hub-mock.sh --keep   # leave the stacks running (for interactive work)
#
# Topology (all localhost):
#   fake vault A :8791 (vault "default")  ← Prism Server A :8787 (FEDERATION_ENABLED)
#   fake vault B :8793 (vault "fed-b")    ← Prism Server B :8788 (FEDERATION_ENABLED)
# The harness talks only to the two servers (HTTP + /collab WS) and asserts
# convergence through each gateway — exactly like the real thing.
#
# Env files are .env.mock-a / .env.mock-b (gitignored via .env*); DBs are
# prism-mock-a.db / prism-mock-b.db, removed on every run for determinism.

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SERVER_DIR="$ROOT/apps/server"
KEEP=0
[ "${1:-}" = "--keep" ] && KEEP=1

A_PORT=8787 B_PORT=8788 VA_PORT=8791 VB_PORT=8793
LOG_A="${TMPDIR:-/tmp}/prism-mock-a.log"
LOG_B="${TMPDIR:-/tmp}/prism-mock-b.log"
LOG_VA="${TMPDIR:-/tmp}/fake-vault-a.log"
LOG_VB="${TMPDIR:-/tmp}/fake-vault-b.log"

say()  { printf '\033[1;36m[two-hub-mock]\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31m[two-hub-mock]\033[0m %s\n' "$*" >&2; exit 1; }
[ -d "$ROOT/node_modules" ] || fail "run npm install first"

port_busy() { (exec 3<>"/dev/tcp/127.0.0.1/$1") 2>/dev/null && { exec 3>&- 3<&-; return 0; } || return 1; }
for p in $A_PORT $B_PORT $VA_PORT $VB_PORT; do
  port_busy "$p" && fail "port $p busy — stop what's on it or edit the ports in this script"
done

PIDS=()
cleanup() {
  [ "$KEEP" = 1 ] && { say "--keep: stacks left running (pids: ${PIDS[*]:-})"; return; }
  for pid in "${PIDS[@]:-}"; do kill "$pid" 2>/dev/null || true; done
  wait 2>/dev/null || true
}
trap cleanup EXIT INT TERM

# ── keys + env files ──────────────────────────────────────────────────────────
say "generating Ed25519 peer identities…"
KEY_A=$(cd "$SERVER_DIR" && node --import tsx -e 'import("./src/auth/peer.ts").then(m=>console.log(m.generateKeyPairB64url().privateKeyB64url))')
KEY_B=$(cd "$SERVER_DIR" && node --import tsx -e 'import("./src/auth/peer.ts").then(m=>console.log(m.generateKeyPairB64url().privateKeyB64url))')

mkenv() { # $1=file $2=port $3=vault-port $4=vault-name $5=owner $6=db $7=key $8=collab-token
  cat > "$SERVER_DIR/$1" <<EOF
# generated by scripts/two-hub-mock.sh — mock federation stack (safe to delete)
APP_ORIGIN=http://localhost:$2
PORT=$2
PARACHUTE_URL=http://127.0.0.1:$3
PARACHUTE_VAULT=$4
PARACHUTE_TOKEN=mock-vault-token-$4
SESSION_SECRET=mock-session-secret-$4-not-production
CAPABILITY_SECRET=mock-capability-secret-$4-not-production
COLLAB_TOKEN=$8
OWNER_EMAIL=$5
DB_PATH=$6
PEER_SIGNING_KEY=$7
FEDERATION_ENABLED=true
EOF
  chmod 600 "$SERVER_DIR/$1"
}
mkenv .env.mock-a $A_PORT $VA_PORT default ownerA@mock.local ./prism-mock-a.db "$KEY_A" collab_mock_a_token
mkenv .env.mock-b $B_PORT $VB_PORT fed-b   ownerB@mock.local ./prism-mock-b.db "$KEY_B" collab_mock_b_token
rm -f "$SERVER_DIR"/prism-mock-a.db* "$SERVER_DIR"/prism-mock-b.db*

# ── fake vaults ───────────────────────────────────────────────────────────────
say "starting fake vaults (:$VA_PORT default, :$VB_PORT fed-b)…"
: > "$LOG_VA"; : > "$LOG_VB"
FAKE_VAULT_PORT=$VA_PORT FAKE_VAULT_NAME=default node "$ROOT/scripts/e2e/fake-vault.mjs" >> "$LOG_VA" 2>&1 &
PIDS+=($!)
FAKE_VAULT_PORT=$VB_PORT FAKE_VAULT_NAME=fed-b node "$ROOT/scripts/e2e/fake-vault.mjs" >> "$LOG_VB" 2>&1 &
PIDS+=($!)

# ── prism servers ─────────────────────────────────────────────────────────────
say "starting Prism Server A (:$A_PORT) and B (:$B_PORT)…"
: > "$LOG_A"; : > "$LOG_B"
(cd "$SERVER_DIR" && exec node --env-file=.env.mock-a --import tsx src/index.ts) >> "$LOG_A" 2>&1 &
PIDS+=($!)
(cd "$SERVER_DIR" && exec node --env-file=.env.mock-b --import tsx src/index.ts) >> "$LOG_B" 2>&1 &
PIDS+=($!)

wait_up() { # $1=port $2=log
  for i in $(seq 1 60); do
    if curl -s --noproxy '*' -o /dev/null "http://localhost:$1/auth/me" 2>/dev/null; then return 0; fi
    sleep 0.5
  done
  tail -20 "$2"; fail "server on :$1 did not come up"
}
wait_up $A_PORT "$LOG_A"; wait_up $B_PORT "$LOG_B"
say "both hubs up (logs: $LOG_A · $LOG_B)"

[ "$KEEP" = 1 ] && { say "stacks running — Hub A http://localhost:$A_PORT, Hub B http://localhost:$B_PORT"; say "env files: apps/server/.env.mock-{a,b}"; exit 0; }

# ── the harness ───────────────────────────────────────────────────────────────
say "running verify-two-hub.ts…"
(
  cd "$SERVER_DIR" &&
  HUB_A_ENV="$SERVER_DIR/.env.mock-a" \
  HUB_B_ENV="$SERVER_DIR/.env.mock-b" \
  node --import tsx scripts/verify-two-hub.ts
)
say "two-hub mock harness PASSED"
